package clang;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;

/**
 * <i>native declaration : src/main/c/clang-c/Index.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CXCompletionResult extends Structure {
    /**
     * \brief The kind of entity that this completion refers to.<br>
     * * The cursor kind will be a macro, keyword, or a declaration (one of the<br>
     * *Decl cursor kinds), describing the entity that the completion is<br>
     * referring to.<br>
     * * \todo In the future, we would like to provide a full cursor, to allow<br>
     * the client to extract additional information from declaration.<br>
     *
     * @see CXCursorKind<br>
     *      C type : CXCursorKind
     */
    public int CursorKind;
    /**
     * \brief The code-completion string that describes how to insert this<br>
     * code-completion result into the editing buffer.<br>
     * C type : CXCompletionString
     */
    public Pointer CompletionString;

    public CXCompletionResult() {
        super();
        initFieldOrder();
    }

    protected void initFieldOrder() {
        setFieldOrder(new String[]{"CursorKind", "CompletionString"});
    }

    /**
     * @param CursorKind       \brief The kind of entity that this completion refers to.<br>
     *                         * The cursor kind will be a macro, keyword, or a declaration (one of the<br>
     *                         *Decl cursor kinds), describing the entity that the completion is<br>
     *                         referring to.<br>
     *                         * \todo In the future, we would like to provide a full cursor, to allow<br>
     *                         the client to extract additional information from declaration.<br>
     * @param CompletionString \brief The code-completion string that describes how to insert this<br>
     *                         code-completion result into the editing buffer.<br>
     *                         C type : CXCompletionString
     * @see CXCursorKind<br>
     *      C type : CXCursorKind<br>
     */
    public CXCompletionResult(int CursorKind, Pointer CompletionString) {
        super();
        this.CursorKind = CursorKind;
        this.CompletionString = CompletionString;
        initFieldOrder();
    }

    public static class ByReference extends CXCompletionResult implements Structure.ByReference {

    }

    public static class ByValue extends CXCompletionResult implements Structure.ByValue {

    }
}
