package clang;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;

/**
 * <i>native declaration : src/main/c/clang-c/Index.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CXIdxLoc extends Structure {
    /// C type : void*[2]
    public Pointer[] ptr_data = new Pointer[2];
    public int int_data;

    public CXIdxLoc() {
        super();
        initFieldOrder();
    }

    protected void initFieldOrder() {
        setFieldOrder(new String[]{"ptr_data", "int_data"});
    }

    /// @param ptr_data C type : void*[2]
    public CXIdxLoc(Pointer ptr_data[], int int_data) {
        super();
        if (ptr_data.length != this.ptr_data.length)
            throw new IllegalArgumentException("Wrong array size !");
        this.ptr_data = ptr_data;
        this.int_data = int_data;
        initFieldOrder();
    }

    public static class ByReference extends CXIdxLoc implements Structure.ByReference {

    }

    public static class ByValue extends CXIdxLoc implements Structure.ByValue {

    }
}
