package clang;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.ptr.PointerByReference;

/**
 * <i>native declaration : src/main/c/clang-c/Index.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CXIdxEntityInfo extends Structure {
    /**
     * @see CXIdxEntityKind<br>
     *      C type : CXIdxEntityKind
     */
    public int kind;
    /**
     * @see CXIdxEntityCXXTemplateKind<br>
     *      C type : CXIdxEntityCXXTemplateKind
     */
    public int templateKind;
    /**
     * @see CXIdxEntityLanguage<br>
     *      C type : CXIdxEntityLanguage
     */
    public int lang;
    /// C type : const char*
    public Pointer name;
    /// C type : const char*
    public Pointer USR;
    /// C type : CXCursor
    public CXCursor cursor;
    /// C type : const CXIdxAttrInfo**
    public PointerByReference attributes;
    public int numAttributes;

    public CXIdxEntityInfo() {
        super();
        initFieldOrder();
    }

    protected void initFieldOrder() {
        setFieldOrder(new String[]{"kind", "templateKind", "lang", "name", "USR", "cursor", "attributes", "numAttributes"});
    }

    /**
     * @param kind         @see CXIdxEntityKind<br>
     *                     C type : CXIdxEntityKind<br>
     * @param templateKind @see CXIdxEntityCXXTemplateKind<br>
     *                     C type : CXIdxEntityCXXTemplateKind<br>
     * @param lang         @see CXIdxEntityLanguage<br>
     *                     C type : CXIdxEntityLanguage<br>
     * @param name         C type : const char*<br>
     * @param USR          C type : const char*<br>
     * @param cursor       C type : CXCursor<br>
     * @param attributes   C type : const CXIdxAttrInfo**
     */
    public CXIdxEntityInfo(int kind, int templateKind, int lang, Pointer name, Pointer USR, CXCursor cursor, PointerByReference attributes, int numAttributes) {
        super();
        this.kind = kind;
        this.templateKind = templateKind;
        this.lang = lang;
        this.name = name;
        this.USR = USR;
        this.cursor = cursor;
        this.attributes = attributes;
        this.numAttributes = numAttributes;
        initFieldOrder();
    }

    public static class ByReference extends CXIdxEntityInfo implements Structure.ByReference {

    }

    public static class ByValue extends CXIdxEntityInfo implements Structure.ByValue {

    }
}
