package clang;
import com.sun.jna.Structure;
/**
 * <i>native declaration : src/main/c/clang-c/Index.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CXIdxContainerInfo extends Structure {
	/// C type : CXCursor
	public CXCursor cursor;
	public CXIdxContainerInfo() {
		super();
		initFieldOrder();
	}
	protected void initFieldOrder() {
		setFieldOrder(new String[]{"cursor"});
	}
	/// @param cursor C type : CXCursor
	public CXIdxContainerInfo(CXCursor cursor) {
		super();
		this.cursor = cursor;
		initFieldOrder();
	}
	public static class ByReference extends CXIdxContainerInfo implements Structure.ByReference {
		
	};
	public static class ByValue extends CXIdxContainerInfo implements Structure.ByValue {
		
	};
}
