package clang;

import com.sun.jna.Structure;

/**
 * <i>native declaration : src/main/c/clang-c/Index.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CXIdxObjCPropertyDeclInfo extends Structure {
    /// C type : const CXIdxDeclInfo*
    public clang.CXIdxDeclInfo.ByReference declInfo;
    /// C type : const CXIdxEntityInfo*
    public clang.CXIdxEntityInfo.ByReference getter;
    /// C type : const CXIdxEntityInfo*
    public clang.CXIdxEntityInfo.ByReference setter;

    public CXIdxObjCPropertyDeclInfo() {
        super();
        initFieldOrder();
    }

    protected void initFieldOrder() {
        setFieldOrder(new String[]{"declInfo", "getter", "setter"});
    }

    /**
     * @param declInfo C type : const CXIdxDeclInfo*<br>
     * @param getter   C type : const CXIdxEntityInfo*<br>
     * @param setter   C type : const CXIdxEntityInfo*
     */
    public CXIdxObjCPropertyDeclInfo(clang.CXIdxDeclInfo.ByReference declInfo, clang.CXIdxEntityInfo.ByReference getter, clang.CXIdxEntityInfo.ByReference setter) {
        super();
        this.declInfo = declInfo;
        this.getter = getter;
        this.setter = setter;
        initFieldOrder();
    }

    public static class ByReference extends CXIdxObjCPropertyDeclInfo implements Structure.ByReference {

    }

    public static class ByValue extends CXIdxObjCPropertyDeclInfo implements Structure.ByValue {

    }
}
