package clang;

import com.sun.jna.Structure;

/**
 * <i>native declaration : src/main/c/clang-c/Index.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CXIdxObjCContainerDeclInfo extends Structure {
    /// C type : const CXIdxDeclInfo*
    public clang.CXIdxDeclInfo.ByReference declInfo;
    /**
     * @see CXIdxObjCContainerKind<br>
     *      C type : CXIdxObjCContainerKind
     */
    public int kind;

    public CXIdxObjCContainerDeclInfo() {
        super();
        initFieldOrder();
    }

    protected void initFieldOrder() {
        setFieldOrder(new String[]{"declInfo", "kind"});
    }

    /**
     * @param declInfo C type : const CXIdxDeclInfo*<br>
     * @param kind     @see CXIdxObjCContainerKind<br>
     *                 C type : CXIdxObjCContainerKind
     */
    public CXIdxObjCContainerDeclInfo(clang.CXIdxDeclInfo.ByReference declInfo, int kind) {
        super();
        this.declInfo = declInfo;
        this.kind = kind;
        initFieldOrder();
    }

    public static class ByReference extends CXIdxObjCContainerDeclInfo implements Structure.ByReference {

    }

    public static class ByValue extends CXIdxObjCContainerDeclInfo implements Structure.ByValue {

    }
}
