package clang;
import com.sun.jna.Structure;
/**
 * <i>native declaration : src/main/c/clang-c/Index.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CXIdxObjCCategoryDeclInfo extends Structure {
	/// C type : const CXIdxObjCContainerDeclInfo*
	public clang.CXIdxObjCContainerDeclInfo.ByReference containerInfo;
	/// C type : const CXIdxEntityInfo*
	public clang.CXIdxEntityInfo.ByReference objcClass;
	/// C type : CXCursor
	public CXCursor classCursor;
	/// C type : CXIdxLoc
	public CXIdxLoc classLoc;
	/// C type : const CXIdxObjCProtocolRefListInfo*
	public clang.CXIdxObjCProtocolRefListInfo.ByReference protocols;
	public CXIdxObjCCategoryDeclInfo() {
		super();
		initFieldOrder();
	}
	protected void initFieldOrder() {
		setFieldOrder(new String[]{"containerInfo", "objcClass", "classCursor", "classLoc", "protocols"});
	}
	/**
	 * @param containerInfo C type : const CXIdxObjCContainerDeclInfo*<br>
	 * @param objcClass C type : const CXIdxEntityInfo*<br>
	 * @param classCursor C type : CXCursor<br>
	 * @param classLoc C type : CXIdxLoc<br>
	 * @param protocols C type : const CXIdxObjCProtocolRefListInfo*
	 */
	public CXIdxObjCCategoryDeclInfo(clang.CXIdxObjCContainerDeclInfo.ByReference containerInfo, clang.CXIdxEntityInfo.ByReference objcClass, CXCursor classCursor, CXIdxLoc classLoc, clang.CXIdxObjCProtocolRefListInfo.ByReference protocols) {
		super();
		this.containerInfo = containerInfo;
		this.objcClass = objcClass;
		this.classCursor = classCursor;
		this.classLoc = classLoc;
		this.protocols = protocols;
		initFieldOrder();
	}
	public static class ByReference extends CXIdxObjCCategoryDeclInfo implements Structure.ByReference {
		
	};
	public static class ByValue extends CXIdxObjCCategoryDeclInfo implements Structure.ByValue {
		
	};
}
