package clang;

import com.sun.jna.NativeLong;
import com.sun.jna.Structure;

/**
 * <i>native declaration : src/main/c/clang-c/Index.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CXTUResourceUsageEntry extends Structure {
    /**
     * \brief The memory usage category.<br>
     *
     * @see CXTUResourceUsageKind<br>
     *      C type : CXTUResourceUsageKind
     */
    public int kind;
    /**
     * \brief Amount of resources used. <br>
     * The units will depend on the resource kind.
     */
    public NativeLong amount;

    public CXTUResourceUsageEntry() {
        super();
        initFieldOrder();
    }

    protected void initFieldOrder() {
        setFieldOrder(new String[]{"kind", "amount"});
    }

    /**
     * @param kind   \brief The memory usage category.<br>
     * @param amount \brief Amount of resources used. <br>
     *               The units will depend on the resource kind.
     * @see CXTUResourceUsageKind<br>
     *      C type : CXTUResourceUsageKind<br>
     */
    public CXTUResourceUsageEntry(int kind, NativeLong amount) {
        super();
        this.kind = kind;
        this.amount = amount;
        initFieldOrder();
    }

    public static class ByReference extends CXTUResourceUsageEntry implements Structure.ByReference {

    }

    public static class ByValue extends CXTUResourceUsageEntry implements Structure.ByValue {

    }
}
